[build]
  # 1. Create a config.js file with the key
  # 2. Install python libraries
  # 3. Run the python converter
  command = "echo \"const CONFIG = { YT_KEY: '$YOUTUBE_API_KEY' };\" > js/config.js && pip install -r requirements.txt && python data/convert.py"
  
  publish = "."